version: "3.9"

services:
  api:
    build: .
    working_dir: /code
    command: uvicorn web_scraper_server.main:app --host 0.0.0.0 --port 8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
    links:
      - db
    environment:
      PORT: 8000
      DATABASE_HOST: db
    restart: unless-stopped

  db:
    image: postgres:15-alpine
    volumes:
      - postgres:/data/postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: mydb
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
    restart: unless-stopped

volumes:
  postgres:
