version: "3.9"

services:
  api:
    build: .
    working_dir: /code
    command: uvicorn web_scraper_server.main:app --host 0.0.0.0 --port 8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
    links:
      - db
    restart: unless-stopped
    env_file:
      - envs/docker.env

  scarper:
    build: .
    working_dir: /code
    command: bash periodic_crawl.sh
    volumes:
      - .:/code
    depends_on:
      - db
    links:
      - db
    restart: unless-stopped
    env_file:
      - envs/docker.env

  db:
    image: postgres:15-alpine
    volumes:
      - postgres:/data/postgres
    ports:
      - "5432:5432"
    restart: unless-stopped
    env_file:
      - envs/docker.env

volumes:
  postgres:
